//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demiady
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Account
    {
        public int Acc_ID { get; set; }
        [Required(ErrorMessage = "من فضلك ادخل الشهر")]
        [Display(Name = "الشهر")]
        public string Month { get; set; }
        [Display(Name = "الربح الشهري")]
        public int Gained { get; set; }
        [Display(Name = "الدخل الشهري للبضاعه المباعه")]
        public int In_Account { get; set; }
        [Display(Name = "مجموع التوريدات")]
        public int Out_Account { get; set; }
        [Display(Name = "العهدة")]
        public int Wallet { get; set; }
    }
}
