//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demiady
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.TransferEmps = new HashSet<TransferEmp>();
        }

        public int Emp_ID { get; set; }
        [Display(Name = "اسم العامل")]
        [Required(ErrorMessage = "من فضلك ادخل اسم العامل")]
        public string Name { get; set; }
        [Display(Name = "قيمة المرتب")]
        [Required(ErrorMessage = "من فضلك ادخل القيمة")]
        [Range(1, Int32.MaxValue, ErrorMessage = "القيمة يجب ان تكون اكبر من ال 0 ")]
        public int Salary { get; set; }
        [Display(Name = "واصل له ")]
        [Required(ErrorMessage = "من فضلك ادخل القيمة")]
        [Range(0, Int32.MaxValue, ErrorMessage = "القيمة يجب ان تكون اكبر من ال 0 ")]
        public int Wasel { get; set; }
        [Display(Name = "الباقي")]
        [Required(ErrorMessage = "من فضلك ادخل القيمة")]
        [Range(0, Int32.MaxValue, ErrorMessage = "القيمة يجب ان تكون اكبر من ال 0 ")]
        public int Ba2y { get; set; }
        [Display(Name = "تاريخ القبض")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        [DataType(DataType.Date)]
        [Required(ErrorMessage = "من فضلك ادخل التاريخ")]
        public System.DateTime Date { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferEmp> TransferEmps { get; set; }
    }
}
