//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demiady
{
    using System;
    using System.Collections.Generic;
    
    public partial class Retainer
    {
        public int Ret_ID { get; set; }
        public System.DateTime Ret_Date { get; set; }
        public string Client_Name { get; set; }
        public int Prod_Price { get; set; }
        public int Prod_Count { get; set; }
        public int ProdMain_Price { get; set; }
        public int Prod_gain { get; set; }
        public int Ret_Value { get; set; }
        public System.DateTime Due_date { get; set; }
        public int Prod_ID { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
