//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demiady
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Sale
    {

        public int Sal_ID { get; set; }
        [Display(Name = "اسم العميل")]
        [Required(ErrorMessage = "من فضلك ادخل اسم العميل")]
        public string Client_Name { get; set; }
        [Display(Name = "سعر بيع المنتج")]
        [Required(ErrorMessage = "من فضلك ادخل السعر")]
        [Range(1, Int32.MaxValue, ErrorMessage = "القيمة يجب ان تكون اكبر من ال 0 ")]
        public int Prod_Price { get; set; }
        [Display(Name = "العدد")]
        [Required(ErrorMessage = "من فضلك ادخل العدد")]
        [Range(1, Int32.MaxValue, ErrorMessage = "القيمة يجب ان تكون اكبر من ال 0 ")]
        public int Prod_Count { get; set; }
        [Display(Name = "السعر الاصلي للمنتج")]
        [Required(ErrorMessage = "من فضلك ادخل السعر")]
        [Range(1, Int32.MaxValue, ErrorMessage = "القيمة يجب ان تكون اكبر من ال 0 ")]
        public int ProdMain_Price { get; set; }
        [Display(Name = "المكسب الصافي")]
        [Required(ErrorMessage = "من فضلك ادخل المبلغ")]
        [Range(0, Int32.MaxValue, ErrorMessage = "القيمة يجب ان تكون اكبر من ال 0 ")]
        public int Prod_gain { get; set; }
        [Display(Name = "التاريخ")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        [DataType(DataType.Date)]
        [Required(ErrorMessage = "من فضلك ادخل التاريخ")]
        public System.DateTime Sal_Date { get; set; }
        [Display(Name = "رقم العميل")]
        public string Client_Phone { get; set; }
        public Nullable<int> Prod_ID { get; set; }
        public virtual Product Product { get; set; }
    }
}
