//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demiady
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Store
    {
        public int ID { get; set; }
        [Display(Name = "عدد المنتج")]
        [Range(0, Int32.MaxValue, ErrorMessage = "القيمة يجب ان تكون اكبر من ال 0 او تساويه")]
        public int Prod_Count { get; set; }
        [Display(Name = "اسم المنتج")]
        public Nullable<int> Prod_ID { get; set; }
        public virtual Product Product { get; set; }
    }
}
